# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(verbose_name=b'Date Added')),
                ('img_source', models.CharField(max_length=400)),
                ('tags', models.CharField(max_length=200)),
                ('nsfw_probability', models.IntegerField(default=0)),
            ],
        ),
    ]
